### ISSUE TITLE
Mortal Kombat Trilogy (SLUS00330) 80000004 Error

### ISSUE THREAD

**Issue by ColetteDiskette** [sahlberg/pop-fe#210]
I'm having issue using this tool to create an EBOOT for Mortal Kombat Trilogy (SLUS00330). On POPS 3.72 (which I have to use in order to get the game to not crash trying to load into an actual match) the game fails to start with a `The game could not be started. (80000004)` error. At first I thought it was my Popsloader setup not working properly, but then I tried an EBOOT for MKT that I didn't make and it loaded right up. I noticed that the working EBOOT.PBP was 463.5 MiB while mine was 94.2 MiB, so I tried to create it using the "Use CDDA, not ATRAC3" option, and while it did create a larger EBOOT (480.2 MiB) it gave me the same problems. 

I'm on Arch Linux and am doing the conversions from a known good CHD.

**Comment by Nanando0** [comment]
This seems to happen because the program is injecting the wrong ppf, although I didn't notice any benefits in any of these MKT ppfs for PSP. However, if ppf SLUS-00330 (Rev 1).ppf is injected the MKT should go well.

Anyway, I made a placebo ppf to get around this. In the meantime, put this ppf inside the pop fe ppf folder and convert, your game should now work in 3.72 pops.


[SLUS-00330.zip](https://github.com/user-attachments/files/16450207/SLUS-00330.zip)

**Comment by sahlberg** [comment]
Sorry about that.
I have updated pop-fe to use the ppf in the second comment and started a new build.
Please try https://github.com/sahlberg/pop-fe/actions/runs/10192578639 when it finished building.

**Comment by Nanando0** [comment]
Hey Salbergh I apologize, the correct ppfs are actually the previous ones. I rushed over past tests carried out on these same ppfs. Right here are the ones who have always been in pop fe.


 Today I was able to test it better, I don't know if pop fe always behaved this way, as I completely changed the focus to firmware 6.60/6.61 after the settings appeared.

 What's happening is that after some tests, I noticed that pop fe is not running any game in pops lower than 3.90, no matter if the game uses CDDA/At3 or not, if it uses PPF or some config (although we know that the configs are for 6.60+), so I tested games without the configs, and they actually show the error in any pops below 3.90.

**Comment by sahlberg** [comment]
Thanks. I added them back. I didn't realize that the two revisions of the game has the same disc-id but needs two different PPF files.
I changed the detection to use MD5SUM instead of just the disc-id so this should work better.

I don't know if pop-fe has ever worked on 3.90 or earlier.  I have never tested anything other than current version of pops.

Does games converted with PSX2PSP work on that firmware?
The only reason I could think of is that pop-fe always create a PSTITLEIMG section in the PSAR section of the EBOOT
while PSX2PSP only uses PSTITLEIMG if and only if it is a multidisc game.

Can you try creating a multidisc game with PSX2PSP and see if it works?

**Comment by Nanando0** [comment]
Thank you very much.

Yes, I have already tested all versions of POPsLoader.

Converting with PSX2PSP all games work from 3.02 to 6.61, multidisc games only start working from 3.52, if you try a multidisc below 3.52 the error also occurs.

Using pop fe the games start to work from 3.90 to 6.61.

Exactly, I was suspicious of the PSTITLEIMG section but I'm not sure about that, but it was the only difference I found between the conversions.

I particularly think the pop fe conversion method is more refined, perhaps an added check box for those who want to play games below 3.90 removing the additional PSTITLEIMG would be ideal, so as not to completely remove the original mode that we already use, if that is the problem.

If you want to release a version for me to test, it would be a pleasure.

**Comment by Nanando0** [comment]
I carried out a test by adding a 2 Empty CD for the POP-FE conversion and then the games now work up to 3.52.

**Comment by sahlberg** [comment]
Ok, let me try having an option to remove the PSTITLEIMG section.
I will try to build something tomorrow.

**Comment by sahlberg** [comment]
Can you please try https://github.com/sahlberg/pop-fe/actions/runs/10233903437
It is a test branch named no-pstitleimg for now   but when I clean it up a bit I will merge it to master.

There is no option to tick. IF you create an EBOOT for PSP and IF it contains only a single disk then it will do this autimatically and skip generating a PSTITLEIMG section.

I think some of the fields in the PSISOIMG might have different meanings depending on whether or not a PSTITLEIMG is present or not. This is not an issue now because all the changes are hidden behind 'if no-pstitleimg' conditionals but I want to remove those contionals as much as possible.
I need to do this carefully and need to document these things on the psdevwiki as well.  Some of these fields are missing on the PSISOIMG part of the psp wiki.   And I need to test if these fields are also used on ps3 or if they cause issues.

**Comment by Nanando0** [comment]
> Can you please try https://github.com/sahlberg/pop-fe/actions/runs/10233903437 It is a test branch named no-pstitleimg for now but when I clean it up a bit I will merge it to master.
> 
> There is no option to tick. IF you create an EBOOT for PSP and IF it contains only a single disk then it will do this autimatically and skip generating a PSTITLEIMG section.
> 
> I think some of the fields in the PSISOIMG might have different meanings depending on whether or not a PSTITLEIMG is present or not. This is not an issue now because all the changes are hidden behind 'if no-pstitleimg' conditionals but I want to remove those contionals as much as possible. I need to do this carefully and need to document these things on the psdevwiki as well. Some of these fields are missing on the PSISOIMG part of the psp wiki. And I need to test if these fields are also used on ps3 or if they cause issues.

It was tested:

1 CD game > POPs 3.02 to 6.61 boot working perfectly.

Mortal Kombat Trilogy working with PPF applied correctly, normal At3 conversion, normal boot in POPs 3.72.

Game with more than 1 CD, multi-disc EBOOT > POPs 3.52 to 6.61 boot working normally. POPs below 3.52 do not boot Multi-disk EBOOts (Normal operation).

CONFIG correctly applied: Game used for testing: Driver 2

Conclusion:

Normal operation of the converter, POP-FE <3

Thanks.

**Comment by sahlberg** [comment]
Thankyou for testing. I will merge this into master in the next few days.

Just out of curiosity,  why would one want to run an older version of pops?
Is it that different versions of pops have different bugs and some games work better with an older version?

**Comment by ColetteDiskette** [comment]
> Just out of curiosity, why would one want to run an older version of pops? Is it that different versions of pops have different bugs and some games work better with an older version?

Yeah. MKT crashes on newer POPS versions when you try to load a match. Well, it either crashes or locks up showing just the stage background with its music playing. Going older fixes it.

**Comment by sahlberg** [comment]
Thanks for the explanation. 
I have merged this into master now.
Closing as completed.

**Comment by Nanando0** [comment]
> Thankyou for testing. I will merge this into master in the next few days.
> 
> Just out of curiosity, why would one want to run an older version of pops? Is it that different versions of pops have different bugs and some games work better with an older version?

Yes, using MKT as a reference.

We still don't have a fix for it on PSP 6.61 or PSVita.

So the only way to play this game on PSP is using another version of POPs, and on PSVita using Retroarch, as it is incompatible with POPsLoader.

The same happens with other games like Monkey Hero, Destruction Derby 2 etc...

Thanks for the latest version.
